FROM node:20-slim

RUN apt-get update && apt-get install -y \
    gcc g++ python3 \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

EXPOSE 3000
RUN npm install
CMD ["npm", "start"]
